RAG_PERSIST_PATH = "/Users/taoli/persist"
DEFAUT_MODEL = "gpt-3.5-turbo"
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"
SUPPORT_MODEL_LIST= ["gpt-3.5-turbo","gpt-4-turbo-preview","GLM-3-Turbo","GLM-4","moonshot-v1-8k","moonshot-v1-32k"]
SUPPORT_EMBDDING_MODEL_LIST=["text-embedding-3-small","Embedding-2","Baichuan-Text-Embedding"]
CHUNK_SIZE_LIST=[500,1000,2000]
DEFAULT_CHUNK_SIZE=1000
OVERLAP_SIZE_LIST=[100,200,500]
DEFAULT_OVERLAP_SIZE=200
DB_NAME="speedtest"
BACKEND_SEVER_PORT=9099
FRONTEND_SEVER_PORT=7860
DB_URL="mongodb://localhost:27017/"